### ISSUE TITLE
CardMachineRequestorInfo has no public properties and CardPresentPaymentInfo is missing off payment method details

### ISSUE THREAD

**Issue by lewis-green** [dojo-engineering/Dojo.Net.EPOS#1]
We've hit a few issues using this SDK for Tables.

1. CardMachineRequestorInfo  has all of it's properties missing public.
2. PaymentMethodDetails has CardPresentPaymentInfo missing

**Comment by AleksandrMalafeev** [comment]
Hi Lewis, thanks for reporting the issue. We will fix it ASAP!

**Comment by AleksandrMalafeev** [comment]
Hi Lewis, the issue is fixed now, please update to version 1.0.4
Let me know if you have any questions or more issues.
